# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_p', '0006_auto_20160602_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrier',
            name='triggered',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
