# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_p', '0007_auto_20170505_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField()),
                ('message', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='pipeline',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='abort_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='status',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_status', to='django_p.Pipeline'),
        ),
    ]
